main_species: # required configured to be able to run the server

http:
  port: 8080
  mode: release # debug, test, release

mysql:
  host: localhost
  port: 3306
  user: emobase
  password:
  database: emobase_genomics

jobs:
  poll_interval: 1s
  stuck_interval: 5m
  stuck_timeout: 30m

keycloak:
  url: http://localhost:3000
  realm: master
  issuer: "" # defaults to {url}/realms/{realm} if empty
  required_role: default-roles-ibb
  dev_bypass_auth: false

elasticsearch:
  addresses:
    - http://localhost:9200
  index_prefix: emobasegenomics

blast:
  display_name: OGS3 # used as the title prefix in makeblastdb (e.g. "OGS3 Genome")
  db_path: /db # directory where makeblastdb writes its output databases
  container_name: emobase_genomics_blast # name of blast container to restart after new databases are created

uploads:
  dir: ./public/uploads
